import {Component, OnInit, ViewChild} from '@angular/core';
import {MatPaginator} from '@angular/material/paginator';
import {MatSort} from '@angular/material/sort';
import {MatTableDataSource} from '@angular/material/table';
import { ChartsModule } from 'ng2-charts';
import {SelectionModel} from '@angular/cdk/collections';

export interface PeriodicElement {
  Bewerbungsnummer: string;
  Anrede: string;
  Accountname: string;
  'Stadt (Postanschrift)': string;
  'Bundesland (Postanschrift)': string;
  'Land (Postanschrift)': string;
  '1. Bundesland': string;
  '2. Bundesland': string;
  '3. Bundesland': string;
  Einsatzbereiche: string;
  Programmschwerpunkt: string;
}

const ELEMENT_DATA: PeriodicElement[] =
  [
    {
      Bewerbungsnummer: 'BW-0001189',
      Anrede: 'Frau',
      Accountname: 'S. G.',
      'Stadt (Postanschrift)': 'Bobingen',
      'Bundesland (Postanschrift)': 'Baden-Württemberg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Baden-Württemberg',
      '2. Bundesland': 'Berlin',
      '3. Bundesland': 'Hessen',
      Einsatzbereiche: 'Sport; Kreativ & Handwerk; Interkulturell; Musik',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001122',
      Anrede: 'Frau',
      Accountname: 'J. K.',
      'Stadt (Postanschrift)': 'Hamburg',
      'Bundesland (Postanschrift)': 'Hamburg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Hamburg',
      '2. Bundesland': 'Schleswig-Holstein',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001132',
      Anrede: 'Frau',
      Accountname: 'A. B. K.',
      'Stadt (Postanschrift)': 'Hamburg',
      'Bundesland (Postanschrift)': 'Hamburg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Hamburg',
      '2. Bundesland': 'Berlin',
      '3. Bundesland': 'Nordrhein-Westfalen',
      Einsatzbereiche: 'Digitales; Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001124',
      Anrede: 'Frau',
      Accountname: 'S. A.',
      'Stadt (Postanschrift)': 'Hamburg',
      'Bundesland (Postanschrift)': 'Hamburg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Hamburg',
      '2. Bundesland': 'Hessen',
      '3. Bundesland': 'Berlin',
      Einsatzbereiche: 'Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0001131',
      Anrede: 'Frau',
      Accountname: 'M. G.',
      'Stadt (Postanschrift)': 'Karlsruhe',
      'Bundesland (Postanschrift)': 'Baden-Württemberg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Hamburg',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Sport; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0001255',
      Anrede: 'Frau',
      Accountname: 'L. S.',
      'Stadt (Postanschrift)': 'Leipzig',
      'Bundesland (Postanschrift)': 'Sachsen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Sachsen',
      '2. Bundesland': 'Hessen',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Sport; Kreativ & Handwerk; Natur & Umwelt',
      Programmschwerpunkt: 'Keine Präferenz'
    },
    {
      Bewerbungsnummer: 'BW-0001196',
      Anrede: 'Frau',
      Accountname: 'D. L.',
      'Stadt (Postanschrift)': 'Heidelberg',
      'Bundesland (Postanschrift)': 'Baden-Württemberg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Baden-Württemberg',
      '2. Bundesland': 'Hessen',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Digitales; Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Keine Präferenz'
    },
    {
      Bewerbungsnummer: 'BW-0001157',
      Anrede: 'Herr',
      Accountname: 'P. E.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Sport; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I'
    },
    {
      Bewerbungsnummer: 'BW-0001206',
      Anrede: 'Frau',
      Accountname: 'E. B.',
      'Stadt (Postanschrift)': 'Haan',
      'Bundesland (Postanschrift)': 'Hessen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Nordrhein-Westfalen',
      '2. Bundesland': 'Hessen',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Kreativ & Handwerk; Interkulturell; Musik',
      Programmschwerpunkt: 'Keine Präferenz'
    },
    {
      Bewerbungsnummer: 'BW-0001156',
      Anrede: 'Herr',
      Accountname: 'C. O.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Brandenburg',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Keine Präferenz'
    },
    {
      Bewerbungsnummer: 'BW-0001207',
      Anrede: 'Frau',
      Accountname: 'A. P.',
      'Stadt (Postanschrift)': 'Frankfurt am Main',
      'Bundesland (Postanschrift)': 'Hessen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Hessen',
      '2. Bundesland': 'Baden-Württemberg',
      '3. Bundesland': 'Hamburg',
      Einsatzbereiche: 'Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0001266',
      Anrede: 'Frau',
      Accountname: 'C. F.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Brandenburg',
      '3. Bundesland': 'Hamburg',
      Einsatzbereiche: 'Digitales; Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001216',
      Anrede: 'Frau',
      Accountname: 'B. M.',
      'Stadt (Postanschrift)': 'Loxstedt',
      'Bundesland (Postanschrift)': 'Niedersachsen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Digitales; Kreativ & Handwerk; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I'
    },
    {
      Bewerbungsnummer: 'BW-0001221',
      Anrede: 'Frau',
      Accountname: 'B. S.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Digitales; Sport; Kreativ & Handwerk; Interkulturell; Musik',
      Programmschwerpunkt: 'Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001286',
      Anrede: 'Frau',
      Accountname: 'K. L. K.',
      'Stadt (Postanschrift)': 'Bonn',
      'Bundesland (Postanschrift)': 'Nordrhein-Westfalen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Hamburg',
      '3. Bundesland': 'Nordrhein-Westfalen',
      Einsatzbereiche: 'Digitales; Sport; Natur & Umwelt; Interkulturell; Musik',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0001247',
      Anrede: 'Herr',
      Accountname: 'L. E.',
      'Stadt (Postanschrift)': 'Leipzig',
      'Bundesland (Postanschrift)': 'Sachsen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Sachsen',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Digitales; Sport',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Sicherer Übergang! Einsatz in der Sekundarstufe I; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001280',
      Anrede: 'Frau',
      Accountname: 'S. F.',
      'Stadt (Postanschrift)': 'Bochum',
      'Bundesland (Postanschrift)': 'Nordrhein-Westfalen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Nordrhein-Westfalen',
      '2. Bundesland': 'Baden-Württemberg',
      '3. Bundesland': 'Sachsen',
      Einsatzbereiche: 'Digitales; Kreativ & Handwerk; Natur & Umwelt; Interkulturell; Musik',
      Programmschwerpunkt: 'Keine Präferenz'
    },
    {
      Bewerbungsnummer: 'BW-0001252',
      Anrede: 'Frau',
      Accountname: 'E. D.',
      'Stadt (Postanschrift)': 'Paris',
      'Bundesland (Postanschrift)': 'Frankreich',
      'Land (Postanschrift)': 'Frankreich',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Hamburg',
      '3. Bundesland': 'Nordrhein-Westfalen',
      Einsatzbereiche: 'Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001265',
      Anrede: 'Herr',
      Accountname: 'E. W.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Sachsen',
      '2. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Digitales; Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell; Musik',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001276',
      Anrede: 'Herr',
      Accountname: 'P. R.',
      'Stadt (Postanschrift)': 'Leipzig',
      'Bundesland (Postanschrift)': 'Sachsen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Sachsen',
      '2. Bundesland': 'Berlin',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Digitales; Sport; Interkulturell; Musik',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001281',
      Anrede: 'Frau',
      Accountname: 'L. D.',
      'Stadt (Postanschrift)': 'Duisburg',
      'Bundesland (Postanschrift)': 'Nordrhein-Westfalen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Nordrhein-Westfalen',
      '2. Bundesland': 'Berlin',
      '3. Bundesland': 'Berlin',
      Einsatzbereiche: 'Digitales; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0001283',
      Anrede: 'Frau',
      Accountname: 'H. E. D.',
      'Stadt (Postanschrift)': 'Freiburg',
      'Bundesland (Postanschrift)': 'Baden-Württemberg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Hamburg',
      '2. Bundesland': 'Nordrhein-Westfalen',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Sport; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0001343',
      Anrede: 'Frau',
      Accountname: 'V. S.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell; Musik',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0001563',
      Anrede: 'Frau',
      Accountname: 'S. S.',
      'Stadt (Postanschrift)': 'Neuenstein',
      'Bundesland (Postanschrift)': 'Baden-Württemberg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Baden-Württemberg',
      '2. Bundesland': 'Hessen',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Digitales; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001352',
      Anrede: 'Frau',
      Accountname: 'Y. H.',
      'Stadt (Postanschrift)': 'Raunheim',
      'Bundesland (Postanschrift)': 'Baden-Württemberg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Baden-Württemberg',
      '2. Bundesland': 'Nordrhein-Westfalen',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0001364',
      Anrede: 'Frau',
      Accountname: 'S. K.',
      'Stadt (Postanschrift)': 'Leipzig',
      'Bundesland (Postanschrift)': 'Sachsen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Sachsen',
      '2. Bundesland': 'Hessen',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: '',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001791',
      Anrede: 'Herr',
      Accountname: 'M. H.',
      'Stadt (Postanschrift)': 'Hamburg',
      'Bundesland (Postanschrift)': 'Hamburg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Hamburg',
      '2. Bundesland': 'Nordrhein-Westfalen',
      '3. Bundesland': 'Berlin',
      Einsatzbereiche: 'Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0001773',
      Anrede: 'Frau',
      Accountname: 'S. K.',
      'Stadt (Postanschrift)': 'Dresden',
      'Bundesland (Postanschrift)': 'Dresden',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Sachsen',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Digitales; Sport; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001416',
      Anrede: 'Herr',
      Accountname: 'R. S.',
      'Stadt (Postanschrift)': 'Leipzig',
      'Bundesland (Postanschrift)': 'Sachsen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Sachsen',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Digitales; Sport; Kreativ & Handwerk',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001432',
      Anrede: 'Frau',
      Accountname: 'J. H.',
      'Stadt (Postanschrift)': 'Innsbruck',
      'Bundesland (Postanschrift)': 'Österreich',
      'Land (Postanschrift)': 'Österreich',
      '1. Bundesland': 'Baden-Württemberg',
      '2. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Kreativ & Handwerk; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I'
    },
    {
      Bewerbungsnummer: 'BW-0001433',
      Anrede: 'Frau',
      Accountname: 'N. B.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Brandenburg',
      '3. Bundesland': 'Hamburg',
      Einsatzbereiche: 'Digitales; Sport; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001480',
      Anrede: 'Frau',
      Accountname: 'K. S.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Brandenburg',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Digitales; Sport; Interkulturell',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001488',
      Anrede: 'Frau',
      Accountname: 'E. B.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Brandenburg',
      '3. Bundesland': 'Hamburg',
      Einsatzbereiche: 'Sport; Interkulturell',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0001552',
      Anrede: 'Frau',
      Accountname: 'J. S.',
      'Stadt (Postanschrift)': 'Hamburg',
      'Bundesland (Postanschrift)': 'Hamburg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Hamburg',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Digitales; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001546',
      Anrede: 'Frau',
      Accountname: 'J. S.',
      'Stadt (Postanschrift)': 'Borchen',
      'Bundesland (Postanschrift)': 'Nordrhein-Westfalen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Hamburg',
      '2. Bundesland': 'Nordrhein-Westfalen',
      '3. Bundesland': 'Hamburg',
      Einsatzbereiche: 'Digitales; Kreativ & Handwerk; Interkulturell; Musik',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001532',
      Anrede: 'Herr',
      Accountname: 'M. A.',
      'Stadt (Postanschrift)': 'Hamburg',
      'Bundesland (Postanschrift)': 'Hamburg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Hamburg',
      '2. Bundesland': 'Berlin',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Digitales; Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Sicherer Übergang! Einsatz in der Sekundarstufe I; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001766',
      Anrede: 'Frau',
      Accountname: 'L. B.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Berlin',
      '3. Bundesland': 'Hamburg',
      Einsatzbereiche: 'Sport; Natur & Umwelt',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001511',
      Anrede: 'Herr',
      Accountname: 'J. B.',
      'Stadt (Postanschrift)': 'Flörsheim am Main',
      'Bundesland (Postanschrift)': 'Hessen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Hessen',
      '2. Bundesland': 'Baden-Württemberg',
      '3. Bundesland': 'Nordrhein-Westfalen',
      Einsatzbereiche: 'Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0001528',
      Anrede: 'Andere',
      Accountname: 'L. L.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Natur & Umwelt; Interkulturell; Musik',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0001544',
      Anrede: 'Herr',
      Accountname: 'M. R.',
      'Stadt (Postanschrift)': 'Leipzig',
      'Bundesland (Postanschrift)': 'Sachsen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Sachsen',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Kreativ & Handwerk; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001551',
      Anrede: 'Frau',
      Accountname: 'L. B.',
      'Stadt (Postanschrift)': 'Hamburg',
      'Bundesland (Postanschrift)': 'Hamburg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Hamburg',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Sport; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0001574',
      Anrede: 'Frau',
      Accountname: 'J. S.',
      'Stadt (Postanschrift)': 'Lauffen',
      'Bundesland (Postanschrift)': 'Baden-Württemberg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Baden-Württemberg',
      '2. Bundesland': 'Berlin',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Digitales; Sport; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I'
    },
    {
      Bewerbungsnummer: 'BW-0001617',
      Anrede: 'Frau',
      Accountname: 'L. W.',
      'Stadt (Postanschrift)': 'Hergensweiler',
      'Bundesland (Postanschrift)': 'Bayern',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Hessen',
      '2. Bundesland': 'Baden-Württemberg',
      '3. Bundesland': 'Nordrhein-Westfalen',
      Einsatzbereiche: 'Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I'
    },
    {
      Bewerbungsnummer: 'BW-0001752',
      Anrede: 'Herr',
      Accountname: 'C. D.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Hamburg',
      '3. Bundesland': 'Nordrhein-Westfalen',
      Einsatzbereiche: 'Kreativ & Handwerk; Interkulturell; Musik',
      Programmschwerpunkt: 'Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001718',
      Anrede: 'Herr',
      Accountname: 'B. S.',
      'Stadt (Postanschrift)': 'Aachen',
      'Bundesland (Postanschrift)': 'Nordrhein-Westfalen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Baden-Württemberg',
      '2. Bundesland': 'Nordrhein-Westfalen',
      '3. Bundesland': 'Berlin',
      Einsatzbereiche: 'Sport; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Keine Präferenz'
    },
    {
      Bewerbungsnummer: 'BW-0001750',
      Anrede: 'Herr',
      Accountname: 'J. S.',
      'Stadt (Postanschrift)': 'Freiburg im Breisgau',
      'Bundesland (Postanschrift)': 'Baden-Württemberg',
      'Land (Postanschrift)': 'Österreich',
      '1. Bundesland': 'Baden-Württemberg',
      '2. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Natur & Umwelt; Interkulturell; Musik',
      Programmschwerpunkt: 'Keine Präferenz'
    },
    {
      Bewerbungsnummer: 'BW-0001690',
      Anrede: 'Frau',
      Accountname: 'R. L.',
      'Stadt (Postanschrift)': 'Potsdam',
      'Bundesland (Postanschrift)': 'Brandenburg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Brandenburg',
      '2. Bundesland': 'Berlin',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001689',
      Anrede: 'Frau',
      Accountname: 'M. T.',
      'Stadt (Postanschrift)': 'Osnabrück',
      'Bundesland (Postanschrift)': 'Niedersachsen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Baden-Württemberg',
      '2. Bundesland': 'Sachsen',
      '3. Bundesland': 'Schleswig-Holstein',
      Einsatzbereiche: 'Sport; Kreativ & Handwerk; Natur & Umwelt',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001758',
      Anrede: 'Frau',
      Accountname: 'J. B.',
      'Stadt (Postanschrift)': 'Leipzig',
      'Bundesland (Postanschrift)': 'Sachsen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Sachsen',
      '2. Bundesland': 'Brandenburg',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Digitales; Kreativ & Handwerk; Natur & Umwelt',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001712',
      Anrede: 'Herr',
      Accountname: 'F. H.',
      'Stadt (Postanschrift)': 'Jena',
      'Bundesland (Postanschrift)': 'Thüringen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Baden-Württemberg',
      '2. Bundesland': 'Hamburg',
      '3. Bundesland': 'Schleswig-Holstein',
      Einsatzbereiche: 'Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001746',
      Anrede: 'Herr',
      Accountname: 'C. B.',
      'Stadt (Postanschrift)': 'Leipzig',
      'Bundesland (Postanschrift)': 'Sachsen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Sachsen',
      '2. Bundesland': 'Baden-Württemberg',
      '3. Bundesland': 'Schleswig-Holstein',
      Einsatzbereiche: 'Digitales; Kreativ & Handwerk; Natur & Umwelt; Interkulturell; Musik',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001787',
      Anrede: 'Frau',
      Accountname: 'F. B. S.',
      'Stadt (Postanschrift)': 'Hamburg',
      'Bundesland (Postanschrift)': 'Hamburg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Hamburg',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Sport; Natur & Umwelt; Interkulturell; Musik',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001792',
      Anrede: 'Herr',
      Accountname: 'N. B.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Brandenburg',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Digitales; Kreativ & Handwerk; Natur & Umwelt; Interkulturell; Musik',
      Programmschwerpunkt: 'Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001832',
      Anrede: 'Frau',
      Accountname: 'M. P.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Baden-Württemberg',
      '3. Bundesland': 'Brandenburg',
      Einsatzbereiche: 'Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0001896',
      Anrede: 'Herr',
      Accountname: 'J. S.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Baden-Württemberg',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Digitales; Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001895',
      Anrede: 'Frau',
      Accountname: 'H. J.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Brandenburg',
      '3. Bundesland': 'Hamburg',
      Einsatzbereiche: '',
      Programmschwerpunkt: 'Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0001929',
      Anrede: 'Frau',
      Accountname: 'J. F.',
      'Stadt (Postanschrift)': 'Essen',
      'Bundesland (Postanschrift)': 'Nordrhein-Westfalen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Nordrhein-Westfalen',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: '',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0001932',
      Anrede: 'Herr',
      Accountname: 'H. v. B.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Brandenburg',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: '',
      Programmschwerpunkt: 'Keine Präferenz'
    },
    {
      Bewerbungsnummer: 'BW-0001989',
      Anrede: 'Frau',
      Accountname: 'A. S.',
      'Stadt (Postanschrift)': 'Halle',
      'Bundesland (Postanschrift)': 'Sachsen-Anhalt',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Sachsen',
      '2. Bundesland': 'Berlin',
      '3. Bundesland': 'Hamburg',
      Einsatzbereiche: 'Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I'
    },
    {
      Bewerbungsnummer: 'BW-0001982',
      Anrede: 'Frau',
      Accountname: 'K. W.',
      'Stadt (Postanschrift)': 'Mainz',
      'Bundesland (Postanschrift)': 'Rheinland-Pfalz',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Hamburg',
      '3. Bundesland': 'Nordrhein-Westfalen',
      Einsatzbereiche: 'Digitales; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0001986',
      Anrede: 'Frau',
      Accountname: 'J. V. L.',
      'Stadt (Postanschrift)': 'Kiel',
      'Bundesland (Postanschrift)': 'Schleswig-Holstein',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Schleswig-Holstein',
      '2. Bundesland': 'Hamburg',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Sport; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0002078',
      Anrede: 'Herr',
      Accountname: 'T. F.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Nordrhein-Westfalen',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Digitales; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0002143',
      Anrede: 'Herr',
      Accountname: 'P. D.',
      'Stadt (Postanschrift)': 'Karlsruhe',
      'Bundesland (Postanschrift)': 'Baden-Württemberg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Baden-Württemberg',
      '2. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0002063',
      Anrede: 'Frau',
      Accountname: 'L. A.',
      'Stadt (Postanschrift)': 'Köln',
      'Bundesland (Postanschrift)': 'Nordrhein-Westfalen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Nordrhein-Westfalen',
      '2. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Sport; Kreativ & Handwerk; Natur & Umwelt; Musik',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0002131',
      Anrede: 'Herr',
      Accountname: 'M. R.',
      'Stadt (Postanschrift)': 'Bonn',
      'Bundesland (Postanschrift)': 'Nordrhein-Westfalen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Nordrhein-Westfalen',
      '2. Bundesland': 'Hamburg',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Digitales; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0002098',
      Anrede: 'Herr',
      Accountname: 'F. D.',
      'Stadt (Postanschrift)': 'Wendeburg',
      'Bundesland (Postanschrift)': 'Niedersachsen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Hamburg',
      '2. Bundesland': 'Berlin',
      '3. Bundesland': 'Nordrhein-Westfalen',
      Einsatzbereiche: 'Digitales; Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Keine Präferenz'
    },
    {
      Bewerbungsnummer: 'BW-0002173',
      Anrede: 'Frau',
      Accountname: 'N. R.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Sachsen',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0002188',
      Anrede: 'Frau',
      Accountname: 'M. J.',
      'Stadt (Postanschrift)': 'Leipzig',
      'Bundesland (Postanschrift)': 'Sachsen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Sachsen',
      '2. Bundesland': 'Sachsen',
      '3. Bundesland': 'Sachsen',
      Einsatzbereiche: 'Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Keine Präferenz'
    },
    {
      Bewerbungsnummer: 'BW-0002205',
      Anrede: 'Frau',
      Accountname: 'L. M. D.',
      'Stadt (Postanschrift)': 'Essen',
      'Bundesland (Postanschrift)': 'Nordrhein-Westfalen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Nordrhein-Westfalen',
      '2. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Digitales; Sport; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0002230',
      Anrede: 'Frau',
      Accountname: 'M. G.',
      'Stadt (Postanschrift)': 'Dresden',
      'Bundesland (Postanschrift)': 'Sachsen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Sachsen',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Digitales; Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0002246',
      Anrede: 'Herr',
      Accountname: 'D. P.',
      'Stadt (Postanschrift)': 'Hamburg',
      'Bundesland (Postanschrift)': 'Hamburg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Hamburg',
      '2. Bundesland': 'Berlin',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Digitales; Sport; Natur & Umwelt; Musik',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0002271',
      Anrede: 'Frau',
      Accountname: 'K. K.',
      'Stadt (Postanschrift)': 'Frankfurt am Main',
      'Bundesland (Postanschrift)': 'Hessen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Baden-Württemberg',
      '2. Bundesland': 'Nordrhein-Westfalen',
      '3. Bundesland': 'Hamburg',
      Einsatzbereiche: 'Sport; Kreativ & Handwerk; Natur & Umwelt',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I'
    },
    {
      Bewerbungsnummer: 'BW-0002293',
      Anrede: 'Frau',
      Accountname: 'M. L.',
      'Stadt (Postanschrift)': 'Schulzendorf',
      'Bundesland (Postanschrift)': 'Brandenburg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Brandenburg',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Digitales; Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule'
    },
    {
      Bewerbungsnummer: 'BW-0002301',
      Anrede: 'Frau',
      Accountname: 'C. S.',
      'Stadt (Postanschrift)': 'Bielefeld',
      'Bundesland (Postanschrift)': 'Nordrhein-Westfalen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Nordrhein-Westfalen',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0002311',
      Anrede: 'Herr',
      Accountname: 'S. R.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Brandenburg',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Digitales; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0002322',
      Anrede: 'Herr',
      Accountname: 'F. R.',
      'Stadt (Postanschrift)': 'Munderkingen',
      'Bundesland (Postanschrift)': 'Baden-Württemberg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Baden-Württemberg',
      '2. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Digitales; Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell; Musik',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0002335',
      Anrede: 'Herr',
      Accountname: 'M. R.',
      'Stadt (Postanschrift)': 'Mannheim',
      'Bundesland (Postanschrift)': 'Baden-Württemberg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Baden-Württemberg',
      '2. Bundesland': 'Hamburg',
      '3. Bundesland': 'Berlin',
      Einsatzbereiche: 'Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0002369',
      Anrede: 'Frau',
      Accountname: 'K. N.',
      'Stadt (Postanschrift)': 'Leipzig - Mitte',
      'Bundesland (Postanschrift)': 'Sachsen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Berlin',
      '2. Bundesland': 'Sachsen',
      '3. Bundesland': 'Nordrhein-Westfalen',
      Einsatzbereiche: 'Digitales; Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell; Musik',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0002493',
      Anrede: 'Frau',
      Accountname: 'L. D.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Brandenburg',
      '2. Bundesland': 'Hamburg',
      '3. Bundesland': 'Schleswig-Holstein',
      Einsatzbereiche: 'Kreativ & Handwerk; Natur & Umwelt',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I'
    },
    {
      Bewerbungsnummer: 'BW-0002461',
      Anrede: 'Frau',
      Accountname: 'L. H.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Brandenburg',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0002533',
      Anrede: 'Frau',
      Accountname: 'S. H.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Brandenburg',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Digitales; Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0002488',
      Anrede: 'Frau',
      Accountname: 'L. A.',
      'Stadt (Postanschrift)': 'Hamburg',
      'Bundesland (Postanschrift)': 'Hamburg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Hamburg',
      '2. Bundesland': 'Schleswig-Holstein',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Keine Präferenz'
    },
    {
      Bewerbungsnummer: 'BW-0002414',
      Anrede: 'Herr',
      Accountname: 'K. F.',
      'Stadt (Postanschrift)': 'Hamburg',
      'Bundesland (Postanschrift)': 'Hamburg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Hamburg',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Kreativ & Handwerk; Natur & Umwelt; Interkulturell; Musik',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0002428',
      Anrede: 'Frau',
      Accountname: 'R. M.',
      'Stadt (Postanschrift)': 'Brandenburg',
      'Bundesland (Postanschrift)': 'Brandenburg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Ich habe keine Präferenz für mein Einsatzbundesland.',
      '2. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0002511',
      Anrede: 'Herr',
      Accountname: 'J. W.',
      'Stadt (Postanschrift)': 'Leipzig',
      'Bundesland (Postanschrift)': 'Sachsen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Sachsen',
      '2. Bundesland': 'Brandenburg',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0002456',
      Anrede: 'Frau',
      Accountname: 'S. B.',
      'Stadt (Postanschrift)': 'Benningen am Neckar',
      'Bundesland (Postanschrift)': 'Bayern',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Baden-Württemberg',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Digitales; Sport; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Keine Präferenz'
    },
    {
      Bewerbungsnummer: 'BW-0002489',
      Anrede: 'Frau',
      Accountname: 'N. K.',
      'Stadt (Postanschrift)': 'Hamburg',
      'Bundesland (Postanschrift)': 'Hamburg',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Hamburg',
      '2. Bundesland': 'Schleswig-Holstein',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Kreativ & Handwerk; Natur & Umwelt; Interkulturell; Musik',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0002474',
      Anrede: 'Frau',
      Accountname: 'N. H.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Hamburg',
      '2. Bundesland': 'Schleswig-Holstein',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0002475',
      Anrede: 'Frau',
      Accountname: 'C. L.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Hamburg',
      '2. Bundesland': 'Schleswig-Holstein',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Digitales; Kreativ & Handwerk; Natur & Umwelt',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I'
    },
    {
      Bewerbungsnummer: 'BW-0002509',
      Anrede: 'Frau',
      Accountname: 'K. R.',
      'Stadt (Postanschrift)': 'Bayreuth',
      'Bundesland (Postanschrift)': 'Bayern',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Baden-Württemberg',
      '2. Bundesland': 'Sachsen',
      '3. Bundesland': 'Schleswig-Holstein',
      Einsatzbereiche: '',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Neue Perspektiven! Einsatz in berufsbildenden Schulen; Keine Präferenz'
    },
    {
      Bewerbungsnummer: 'BW-0002532',
      Anrede: 'Frau',
      Accountname: 'S. J. G.',
      'Stadt (Postanschrift)': 'Frankfurt an der Oder',
      'Bundesland (Postanschrift)': 'Hessen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Brandenburg',
      '2. Bundesland': 'Baden-Württemberg',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Natur & Umwelt; Interkulturell; Musik',
      Programmschwerpunkt: 'Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0002544',
      Anrede: 'Herr',
      Accountname: 'T. G.',
      'Stadt (Postanschrift)': 'Dresden',
      'Bundesland (Postanschrift)': 'Sachsen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Sachsen',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Kreativ & Handwerk; Interkulturell',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0002558',
      Anrede: 'Herr',
      Accountname: 'J. W.',
      'Stadt (Postanschrift)': 'Aachen',
      'Bundesland (Postanschrift)': 'Nordrhein-Westfalen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Nordrhein-Westfalen',
      '2. Bundesland': 'Hamburg',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Digitales; Kreativ & Handwerk; Interkulturell; Musik',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0002632',
      Anrede: 'Frau',
      Accountname: 'S. M. S.',
      'Stadt (Postanschrift)': 'Bonn',
      'Bundesland (Postanschrift)': 'Nordrhein-Westfalen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Nordrhein-Westfalen',
      '2. Bundesland': 'Sachsen',
      '3. Bundesland': 'Schleswig-Holstein',
      Einsatzbereiche: 'Digitales; Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell; Musik',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: 'BW-0002582',
      Anrede: 'Frau',
      Accountname: 'S. K. S.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Brandenburg',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0002585',
      Anrede: 'Frau',
      Accountname: 'J. H.',
      'Stadt (Postanschrift)': 'Düsseldorf',
      'Bundesland (Postanschrift)': 'Nordrhein-Westfalen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Nordrhein-Westfalen',
      '2. Bundesland': 'Brandenburg',
      '3. Bundesland': 'Hamburg',
      Einsatzbereiche: 'Digitales; Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell; Musik',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0002614',
      Anrede: 'Frau',
      Accountname: 'J. H.',
      'Stadt (Postanschrift)': 'Leipzig',
      'Bundesland (Postanschrift)': 'Sachsen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Sachsen',
      '2. Bundesland': 'Brandenburg',
      '3. Bundesland': 'Schleswig-Holstein',
      Einsatzbereiche: 'Kreativ & Handwerk; Natur & Umwelt',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I'
    },
    {
      Bewerbungsnummer: 'BW-0002617',
      Anrede: 'Frau',
      Accountname: 'L. K.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Brandenburg',
      '2. Bundesland': 'Sachsen',
      '3. Bundesland': 'Hamburg',
      Einsatzbereiche: 'Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0002604',
      Anrede: 'Herr',
      Accountname: 'W. B.',
      'Stadt (Postanschrift)': 'Chemnitz',
      'Bundesland (Postanschrift)': 'Sachsen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Sachsen',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0002602',
      Anrede: 'Herr',
      Accountname: 'J. M.',
      'Stadt (Postanschrift)': 'Berlin',
      'Bundesland (Postanschrift)': 'Berlin',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Brandenburg',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Digitales; Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell; Musik',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0002655',
      Anrede: 'Frau',
      Accountname: 'V. S.',
      'Stadt (Postanschrift)': 'Kaufbeuren',
      'Bundesland (Postanschrift)': 'Bayern',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Baden-Württemberg',
      '2. Bundesland': 'Hamburg',
      '3. Bundesland': 'Brandenburg',
      Einsatzbereiche: 'Kreativ & Handwerk; Natur & Umwelt',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I'
    },
    {
      Bewerbungsnummer: 'BW-0002685',
      Anrede: 'Frau',
      Accountname: 'F. K.',
      'Stadt (Postanschrift)': 'Münster',
      'Bundesland (Postanschrift)': 'Nordrhein-Westfalen',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Nordrhein-Westfalen',
      '2. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      '3. Bundesland': 'Ein anderes Einsatzbundesland kommt für mich nicht in Frage.',
      Einsatzbereiche: 'Kreativ & Handwerk; Natur & Umwelt; Interkulturell',
      Programmschwerpunkt: 'Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen; Neue Perspektiven! Einsatz in berufsbildenden Schulen'
    },
    {
      Bewerbungsnummer: 'BW-0002699',
      Anrede: 'Herr',
      Accountname: 'E. H.',
      'Stadt (Postanschrift)': 'Weßling',
      'Bundesland (Postanschrift)': 'Bayern',
      'Land (Postanschrift)': 'Deutschland',
      '1. Bundesland': 'Sachsen',
      '2. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      '3. Bundesland': 'Alle anderen Einsatzbundesländer haben für mich die gleiche Präferenz.',
      Einsatzbereiche: 'Digitales; Sport; Kreativ & Handwerk; Natur & Umwelt; Interkulturell; Musik',
      Programmschwerpunkt: 'Starke Basis! Einsatz in der Grundschule; Sicherer Übergang! Einsatz in der Sekundarstufe I; Echte Teilhabe! Einsatz in Willkommensklassen'
    },
    {
      Bewerbungsnummer: '',
      Anrede: '',
      Accountname: '',
      'Stadt (Postanschrift)': '',
      'Bundesland (Postanschrift)': '',
      'Land (Postanschrift)': '',
      '1. Bundesland': '',
      '2. Bundesland': '',
      '3. Bundesland': '',
      Einsatzbereiche: '',
      Programmschwerpunkt: ''
    },
    {
      Bewerbungsnummer: '',
      Anrede: '',
      Accountname: '',
      'Stadt (Postanschrift)': '',
      'Bundesland (Postanschrift)': '',
      'Land (Postanschrift)': '',
      '1. Bundesland': '',
      '2. Bundesland': '',
      '3. Bundesland': '',
      Einsatzbereiche: '',
      Programmschwerpunkt: ''
    },
    {
      Bewerbungsnummer: '',
      Anrede: '',
      Accountname: '',
      'Stadt (Postanschrift)': '',
      'Bundesland (Postanschrift)': '',
      'Land (Postanschrift)': '',
      '1. Bundesland': '',
      '2. Bundesland': '',
      '3. Bundesland': '',
      Einsatzbereiche: '',
      Programmschwerpunkt: ''
    },
    {
      Bewerbungsnummer: '',
      Anrede: '',
      Accountname: '',
      'Stadt (Postanschrift)': '',
      'Bundesland (Postanschrift)': '',
      'Land (Postanschrift)': '',
      '1. Bundesland': '',
      '2. Bundesland': '',
      '3. Bundesland': '',
      Einsatzbereiche: '',
      Programmschwerpunkt: ''
    }
  ];


@Component({
  selector: 'app-ranking',
  templateUrl: './ranking.component.html',
  styleUrls: ['./ranking.component.css']
})
export class RankingComponent implements OnInit {
  displayedColumns: string[] = ['select', 'position', 'name', 'weight', 'symbol'];
  dataSource = new MatTableDataSource<PeriodicElement>(ELEMENT_DATA);
  selection = new SelectionModel<PeriodicElement>(true, []);

  chartOptions = {
    responsive: true
  };

  chartData = [
    { data: [330, 600, 260, 700], label: 'Account A' },
    { data: [120, 455, 100, 340], label: 'Account B' },
    { data: [45, 67, 800, 500], label: 'Account C' }
  ];

  chartLabels = ['January', 'February', 'Mars', 'April'];

  onChartClick(event) {
    console.log(event);
  }

  ngOnInit(): void {

  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.dataSource.data.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.dataSource.data.forEach(row => this.selection.select(row));
  }

  /** The label for the checkbox on the passed row */
  checkboxLabel(row?: PeriodicElement): string {
    if (!row) {
      return `${this.isAllSelected() ? 'select' : 'deselect'} all`;
    }
    return `${this.selection.isSelected(row) ? 'deselect' : 'select'} row ${row.Bewerbungsnummer + 1}`;
  }

}
